Replace deprecated ioctl crate with nix
ethercat-rs/ethercat pull request #2
Opened 2020-02-06 17:43 UTC by flosse

@birkenfeld Could you have a look at the used nix macros? At the moment I can't test the code :-\

2020-02-07 06:46 UTC, birkenfeld commented
The `ioctl-sys` crate doesn't seem to be actually deprecated. Only `ioctl` is (but they are unaffiliated, strangely).

2020-02-07 13:27 UTC, flosse commented
> The `ioctl-sys` crate doesn't seem to be actually deprecated. Only `ioctl` is (but they are unaffiliated, strangely).

You're right, `ioctl-sys` is officially not deprecated but the latest release was  Mar 17, 2017 and the latest commit was 20 Apr 2017 whereas the latest nix was released Feb 4, 2020 and is maintained by a large number of contributors.

2020-02-07 15:14 UTC, birkenfeld commented
Sure, but it's small and stable, there's no outstanding issues in the repo, and I don't believe that you have to put out releases just to show activity. `nix`'s scope is much, much broader so there's no surprise it needs (and gets) much more maintenance.

Still, maybe we'll need `nix` for other things in the future, so I'm fine with this (after comments are addressed).  (Can't test with real HW at the moment either, though.)

2020-02-07 15:14 UTC, birkenfeld requested changes

2020-02-07 15:14 UTC, birkenfeld commented on ethercat-sys/src/lib.rs
> +    ioctl_write_ptr!( SELECT_REF_CLOCK    , EC, 0x22, u32);
This one might need to be `ioctl_write_int`. (This ioctl isn't currently used in the Rust code.)

2020-02-07 15:14 UTC, birkenfeld commented on ethercat-sys/src/lib.rs
> +    ioctl_write_int!( SEND                , EC, 0x25);
This looks incorrect; the C header uses `EC_IO()` which would translate to `ioctl_none` while `ioctl_write` uses `IOW`.

The case here seems to be "strange" and you need to use `ioctl_write_int_bad!(SEND, request_code_none!(EC, 0x25))`.

2020-02-07 15:14 UTC, birkenfeld commented on ethercat-sys/src/lib.rs
> +    ioctl_write_int!( DOMAIN_SIZE         , EC, 0x43);
same here

2020-02-11 18:52 UTC, flosse commented
> Sure, but it's small and stable, there's no outstanding issues in the repo

You're right. So lets ignore my PR ;-)
If there will be any problems in the future we can discuss again.

2020-02-11 18:52 UTC, closed without merging